apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  vault-agent-config: |-
    pid_file = "/var/run/secrets/vaultproject.io/pid"

    auto_auth {
            method "kubernetes"  {
                    type = "kubernetes"
                    mount_path = "auth/kubernetes"
                    config = {
                            role = "example"
                            jwt = "@/var/run/secrets/kubernetes.io/serviceaccount/token"
                    }
            }

            sink "file" {
                    type = "file"
                    config = {
                            path = "/var/run/secrets/vaultproject.io/token"
                    }
            }
    }

---
